import {Component,Input,OnChanges,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {JsonPipe} from '@angular/common';
import {api,FleetResult,TargetResult,VectorAsset,VectorInventory,VectorPreview,VectorRows} from '../api';
import {FleetOperationResult} from '../shared/fleet-operation-result';

@Component({selector:'vector-workspace',imports:[FormsModule,JsonPipe,FleetOperationResult],template:`
<div class="toolbar"><button class="primary" (click)="load()" [disabled]="busy()||!selected.length">{{busy()?'Loading…':'Refresh vector inventory'}}</button></div>
<fleet-operation-result [result]="inventory()"/>
<section><h2>Python library availability</h2>
<p class="muted">Check whether a module is discoverable in each selected IRIS instance. Use its Python import name (for example sentence_transformers). This does not load the library or verify its dependencies.</p>
<form class="search" (ngSubmit)="checkLibrary()"><label>Python module<input name="libraryName" [(ngModel)]="libraryName" (ngModelChange)="libraryResult.set(null)" maxlength="128" pattern="[A-Za-z_][A-Za-z0-9_]*" required placeholder="sentence_transformers"></label><button [disabled]="libraryBusy()||!selected.length||!libraryName.trim()">{{libraryBusy()?'Checking…':'Check selected instances'}}</button></form>
@if(libraryError()){<p class="error" role="alert">{{libraryError()}}</p>}
@if(libraryResult();as result){<div class="table-wrap" aria-live="polite"><table><thead><tr><th>INSTANCE</th><th>MODULE</th><th>RESULT</th><th>DETAIL</th></tr></thead><tbody>@for(target of result.results;track target.instanceId){<tr><td>{{target.instanceName}}</td><td>{{target.data?.module||checkedLibrary}}</td><td>{{target.status==='SUCCESS'?(target.data?.available===true?'OK':target.data?.available===false?'NO':'ERROR'):target.status}}</td><td>{{target.data?.message||target.message}}</td></tr>}</tbody></table></div>}
</section>
@if(inventory()){
<div class="dashboard-grid">
  <section><h2>Fleet vector assets</h2><p class="metric">{{assets().length}}</p><p class="muted">VECTOR and EMBEDDING columns discovered through the IRIS class dictionary.</p></section>
  <section><h2>Embedded Python extensions</h2>@for(target of inventory()!.results;track target.instanceId){<p><strong>{{target.instanceName}}</strong> · {{target.data?.extension?.['embeddedPython']?'available':'unavailable'}} · SentenceTransformers {{target.data?.extension?.['sentenceTransformersInstalled']?'installed':'not installed'}}</p>}</section>
</div>
<section><h2>Vector inventory</h2><div class="table-wrap"><table><thead><tr><th>INSTANCE</th><th>NAMESPACE</th><th>ASSET</th><th>TYPE</th><th>DIMENSIONS</th><th>ROWS</th><th>HNSW</th><th>LOCATION</th><th></th></tr></thead><tbody>
@for(item of assets();track item.target.instanceId+item.asset.assetId){<tr><td><strong>{{item.target.instanceName}}</strong></td><td>{{item.asset.namespace}}</td><td>{{item.asset.schema}}.{{item.asset.table}}<br><span class="muted">{{item.asset.column}}</span></td><td>{{item.asset.kind}}<br><span class="muted">{{item.asset.elementType||'model-derived'}}</span></td><td>{{item.asset.dimensions??'unknown'}}</td><td>{{item.asset.rowCount}}</td><td>@if(item.asset.indexes.length){@for(index of item.asset.indexes;track index.name){<span>{{index.name}} · {{index.distance}} (M={{index.m}}, ef={{index.efConstruction}})</span><br>}}@else{<span class="muted">none</span>}</td><td>Data: {{item.asset.dataLocation}}<br>Index: {{item.asset.indexLocation}}<br><span class="muted">{{item.asset.locationStatus}}</span></td><td><button (click)="showRows(item.target,item.asset,false)">Rows</button> <button (click)="showRows(item.target,item.asset,true)">Vector preview</button> @if(item.asset.kind==='VECTOR'&&item.asset.dimensions===4){<button (click)="previewRegenerate(item.target,item.asset)">Regenerate row 1</button>} @if(item.asset.indexes.length){<button (click)="previewIndex(item.target,item.asset,'REBUILD',item.asset.indexes[0].name)">Rebuild</button> <button (click)="previewIndex(item.target,item.asset,'DROP',item.asset.indexes[0].name)">Drop</button>}@else{<button (click)="previewIndex(item.target,item.asset,'CREATE','VectorHNSW')">Create HNSW</button>}</td></tr>}
</tbody></table></div></section>
<section><h2>Embedding configurations</h2><p class="muted">Secret-like JSON keys are redacted by the backend before this data reaches the browser.</p><div class="table-wrap"><table><thead><tr><th>INSTANCE</th><th>NAME</th><th>CLASS</th><th>LENGTH</th><th>CONFIGURATION</th></tr></thead><tbody>@for(item of models();track item.target.instanceId+item.model.name){<tr><td>{{item.target.instanceName}}</td><td>{{item.model.name}}</td><td>{{item.model.embeddingClass}}</td><td>{{item.model.vectorLength??'unknown'}}</td><td><pre>{{item.model.configuration|json}}</pre></td></tr>}</tbody></table></div>
<form (ngSubmit)="testModel()" class="search"><label>Test controlled Embedded Python recipe<input name="modelText" [(ngModel)]="modelText" maxlength="2000" placeholder="Text to vectorize"></label><label>Instance<select name="modelInstance" [(ngModel)]="modelInstance">@for(target of inventory()!.results;track target.instanceId){@if(target.status==='SUCCESS'){<option [value]="target.instanceId">{{target.instanceName}}</option>}}</select></label><button [disabled]="!modelText||!modelInstance">Test</button></form>@if(modelResult()){<pre>{{modelResult()|json}}</pre>}
</section>}
@if(rows();as data){<section><h2>Source data · {{rowTitle()}}</h2><p>Limited to {{data.limit}} rows. Vector values are {{data.vectorsIncluded?'shown on explicit request':'hidden by default'}}.</p><div class="table-wrap"><table><thead><tr>@for(column of data.columns;track column){<th>{{column}}</th>}</tr></thead><tbody>@for(row of data.rows;track $index){<tr>@for(cell of row;track $index){<td>{{cell}}</td>}</tr>}</tbody></table></div><button (click)="rows.set(null)">Close</button></section>}
@if(preview();as plan){<section role="dialog" aria-modal="true"><h2>Confirm {{plan.action}} · {{plan.instanceName}}</h2><p>This operation affects only <strong>{{plan.target}}</strong>.</p><pre>{{plan.sql}}</pre><label>Type {{plan.confirmation}}<input [(ngModel)]="confirmation" autocomplete="off"></label><button (click)="preview.set(null)">Cancel</button><button class="primary" [disabled]="confirmation!==plan.confirmation||busy()" (click)="apply()">Apply</button></section>}
<fleet-operation-result [result]="actionResult()"/>
@if(error()){<p class="error">{{error()}}</p>}
`})
export class VectorWorkspace implements OnChanges {
  libraryName='sentence_transformers';checkedLibrary='';libraryBusy=signal(false);libraryError=signal('');libraryResult=signal<FleetResult<{module:string;available:boolean|null;message:string}>|null>(null);private libraryRequest=0;
  async checkLibrary(){const module=this.libraryName.trim();if(!/^[A-Za-z_][A-Za-z0-9_]{0,127}$/.test(module)||!this.selected.length){this.libraryError.set('Enter a valid top-level module name and select an instance.');return;}const request=++this.libraryRequest;this.libraryBusy.set(true);this.libraryError.set('');this.libraryResult.set(null);this.checkedLibrary=module;try{const result=await api<FleetResult<{module:string;available:boolean|null;message:string}>>('/vector/libraries/check',{instances:this.selected.join(','),module});if(request===this.libraryRequest&&this.libraryName.trim()===module)this.libraryResult.set(result);}catch(e){if(request===this.libraryRequest)this.libraryError.set(e instanceof Error?e.message:'Library check failed');}finally{if(request===this.libraryRequest)this.libraryBusy.set(false);}}
  @Input() selected:string[]=[];busy=signal(false);error=signal('');inventory=signal<FleetResult<VectorInventory>|null>(null);rows=signal<VectorRows|null>(null);rowTitle=signal('');preview=signal<VectorPreview|null>(null);actionResult=signal<FleetResult|null>(null);modelResult=signal<unknown>(null);confirmation='';modelText='';modelInstance='';
  ngOnChanges(){this.libraryRequest++;this.libraryBusy.set(false);this.libraryResult.set(null);if(this.selected.length)void this.load();}
  async load(){this.busy.set(true);this.error.set('');try{const data=await api<FleetResult<VectorInventory>>('/vector/assets?instances='+this.selected.join(','));this.inventory.set(data);if(!this.modelInstance)this.modelInstance=data.results.find(r=>r.status==='SUCCESS')?.instanceId??'';}catch(e){this.fail(e);}finally{this.busy.set(false);}}
  assets(){return (this.inventory()?.results??[]).flatMap(target=>(target.data?.assets??[]).map(asset=>({target,asset})));}
  models(){return (this.inventory()?.results??[]).flatMap(target=>(target.data?.models??[]).map(model=>({target,model})));}
  async showRows(target:TargetResult<VectorInventory>,asset:VectorAsset,include:boolean){try{const result=await api<FleetResult<VectorRows>>(`/vector/assets/${target.instanceId}/${asset.assetId}/rows?includeVector=${include}`);const data=result.results[0]?.data;if(data){this.rows.set(data);this.rowTitle.set(`${target.instanceName} / ${asset.schema}.${asset.table}`);}}catch(e){this.fail(e);}}
  async previewIndex(target:TargetResult<VectorInventory>,asset:VectorAsset,action:string,indexName:string){try{this.confirmation='';this.preview.set(await api<VectorPreview>('/vector/indexes/preview',{instanceId:target.instanceId,assetId:asset.assetId,action,indexName,distance:'Cosine',m:16,efConstruction:64}));}catch(e){this.fail(e);}}
  async previewRegenerate(target:TargetResult<VectorInventory>,asset:VectorAsset){try{this.confirmation='';this.preview.set(await api<VectorPreview>('/vector/regeneration/preview',{instanceId:target.instanceId,assetId:asset.assetId,rowId:1}));}catch(e){this.fail(e);}}
  async apply(){const plan=this.preview();if(!plan)return;this.busy.set(true);try{this.actionResult.set(await api<FleetResult>('/vector/actions/apply',{planId:plan.planId,confirmation:this.confirmation}));this.preview.set(null);await this.load();}catch(e){this.fail(e);}finally{this.busy.set(false);}}
  async testModel(){try{this.modelResult.set(await api('/vector/models/test',{instanceId:this.modelInstance,text:this.modelText}));}catch(e){this.fail(e);}}
  fail(e:unknown){this.error.set(e instanceof Error?e.message:'Vector operation failed');}
}
