quarkus.http.host=0.0.0.0
quarkus.http.limits.max-body-size=64K
quarkus.http.access-log.enabled=false
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=OFF
quarkus.swagger-ui.always-include=false
fleet.allowed-hosts=iris-prod1,iris-prod2,iris-prod3
fleet.instances=[{"id":"prod1","name":"PROD-01","adminBaseUrl":"http://iris-prod1:52773/api/admin","environment":"PRODUCTION DEMO","jdbcHost":"iris-prod1","jdbcPort":1972,"defaultNamespace":"USER","enabled":true},{"id":"prod2","name":"PROD-02","adminBaseUrl":"http://iris-prod2:52773/api/admin","environment":"PRODUCTION DEMO","jdbcHost":"iris-prod2","jdbcPort":1972,"defaultNamespace":"USER","enabled":true},{"id":"prod3","name":"PROD-03","adminBaseUrl":"http://iris-prod3:52773/api/admin","environment":"PRODUCTION DEMO","jdbcHost":"iris-prod3","jdbcPort":1972,"defaultNamespace":"USER","enabled":true}]
fleet.query.max-rows=500
fleet.query.timeout-seconds=15
